addpost/urls.py
from django.urls import path 
from .views import BlogListView,  BlogView

urlpatterns =[
    path('addpost/', BlogListView.as_view(), name='blog-list'),
    path('addpost/index',BlogView.as_view(), name='blog-detail'),
    
]

authentication/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', views.home, name="home"),
    path('signin', views.signin, name="signin"),
    path('signup', views.signup, name="signup"),
    path('signout', views.signout, name="signout")


]

recipiegen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    # path('profilec/', include('profilec.urls')),
    path('', include('addpost.urls')),
    path('',include('search.urls'))
]

search/urls.py
from django.urls import path 
from . import views
# from .views import SearchView
urlpatterns =[
    path('search', views.getval, name='search'),
    
]

addpost/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
diet_choices = (
    ('diabetic friendly', 'diabetic friendly'),
    ('eggetarian', 'eggetarian'),
    ('gluten free','gluten free'),

    ('high protein non vegetarian', 'high protein non vegetarian'),
    ('high protein vegetarian', 'high protein vegetarian'),

    ('no onion no garlic (sattvic)','no onion no garlic (sattvic)'),
    ('non vegetarian', 'non vegetarian'),
    ('vegan', 'vegan'),
    ('vegetarian', 'vegetarian')

)
course_choices = (
    ('appetizer', 'appetizer'),
    ('breakfast', 'breakfast'),
    ('dessert','dessert'),

    ('dinner', 'dinner'),
    ('lunch', 'lunch'),

    ('main course','main course'),
    ('one pot dish', 'one pot dish'),
    ('side dish', 'side dish'),
    ('snack', 'snack')

)

class Blog(models.Model):
    title = models.TextField()
    ingredients = models.TextField()
    body = models.TextField()
    # preptime = models.DecimalField(decimal_places=0, max_digits=3, default=0), 
    course = models.CharField(max_length=20, choices=course_choices, default='appetizer')
    diet = models.CharField(max_length=28, choices=diet_choices, default='diet')
    # describe the project 
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self) :
        return (self.body)

search/models.py
from django.db import models

# Create your models here.

addpost/forms.py
from django import forms
from .models import Blog


    
class BlogForm(forms.ModelForm):
    title = forms.CharField(
        
        label='',
        widget=forms.Textarea(attrs={
        'class' : 'blogtitle',
        'rows' : '1',
        'placeholder': 'Add Title'
        })
    )
    ingredients = forms.CharField(
        
        label='',
        widget=forms.Textarea(attrs={
        'class' : 'blogingred',
        'rows' : '9',
        'placeholder': 'Add Ingredients'
        })
    )
    # preptime = forms.DecimalField(
        
    #     label='Add prep time in min',
    #     decimal_places= 0,

        
    # )
    body = forms.CharField(
        
        label='',
      widget=forms.Textarea(attrs={
        'class' : 'blogcontent',
        'rows' : '15',
        'placeholder': 'Write about the process'
        })
    )  
    
    
   

    class Meta:
        model = Blog
        fields = ['body', 'title','ingredients', 'diet', 'course']

addpost/views.py
from django.shortcuts import render
from django.views import View
from .models import Blog
# Create your views here.
from .forms import BlogForm

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        blogs = Blog.objects.all().order_by('-created_on')
        form = BlogForm()
        context = {
            'blog_list' : blogs,
            'form' :form,
            'name': request.user
        }

        return render(request, 'addpost/blog.html', context)
    def post(self, request, *args, **kwargs):
        blogs = Blog.objects.all().order_by('-created_on')
        form = BlogForm(request.POST)

        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.save()

        context = {
            'blog_list' : blogs,
            'form' :form,
            'name' : request.user
        }

        return render(request, 'addpost/blog.html', context)
        
  
class BlogView(View):
    def get(self, request, *args, **kwargs):
        blogs = Blog.objects.all().order_by('-created_on')
        form = BlogForm()
        context = {
            'blog_list' : blogs,
            'form' :form,
            'name': request.user
        }
        return render(request, 'addpost/blogindex.html', context)
    def post(self, request, *args, **kwargs):
        blogs = Blog.objects.all().order_by('-created_on')
        form = BlogForm()
        context = {
            'blog_list' : blogs,
            'form' :form,
            'name': request.user
        }
        return render(request, 'addpost/blogindex.html', context)
        

authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from addpost.models import Blog
from addpost.forms import BlogForm
def home(request):
    return render(request, 'authentication/home.html')


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
    
        blogs = Blog.objects.all().order_by('-created_on')
        form = BlogForm()
        context = {
            'blog_list' : blogs,
            'form' :form,
            'name': request.user
        }
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            return render(request, 'addpost/blogindex.html', context)


        else:
            messages.error(request, "Wrong Credentials")
            return redirect('signin')



    return render(request, 'authentication/signin.html')





def signup(request):
    if request.method == "POST":

        username = request.POST['username']
        name = request.POST['name']
        password = request.POST['password']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exist!")
            return redirect('/signup')
        
        
        if len(username)>10:
            messages.error(request, "Username less than 10 characters please")
            return redirect('/signup')


        if not username.isalnum():
            messages.error(request, "Username should be Alpha Numeric")
            return redirect('/signup')



        myuser = User.objects.create_user(username,' ',password)
        myuser.first_name = name
        myuser.save()

        messages.success(request, "Your account created successfully")

        return redirect('signin')

    return render(request, 'authentication/signup.html')




def signout(request):
    logout(request)
    messages.success(request, 'logout sucess')
    return redirect('home')

search/views.py
from django.http import HttpResponse
from django.template import loader
from addpost.models import Blog
from django.shortcuts import render
from django.views import View

        
def getval(request):
    context = {
        'blog_list' : "",
        'name': request.user



    }
    if(request.method == "POST"):
        diet = request.POST.get('diet')
        course = request.POST.get('course')
        print(diet)
        blogs = Blog.objects.filter(diet=diet, course = course)
            
        context = {
            'blog_list' : blogs,
            
            'name': request.user
        }
        return render(request, 'search/index.html', context)
    return render(request, 'search/index.html', context)
        
    
   

templates/addpost/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mainpage.css' %}">
    <link rel="stylesheet" href="{% static 'blog.css' %}">
    <title>Blog</title>
    <style>
        /* mainpage.css */
       body {
      
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)),url({%static 'cover.jpg' %});
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
           

        }
        .add {
            min-height: 100vh;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        
        }

        
        
        .menu{
            float: right;
            list-style:none;
            margin-top: 30px;
            margin-right: 10px;
        }
        .menu li{
            display: inline-block;
        }
        .menu li a{
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            text-transform: uppercase;
            font-weight: bold;
            font-size: 15px;
        }
        .menu li a:hover{
            background: #fff;
            color:#333;
            border-radius: 10px;
        }
        .logo{
            float: left;
            margin-top: 25px;
            margin-left: 10px;
            color: #fff;
            font-size: 1.5em;
            text-transform: uppercase;
            font-weight: bold;
        }


    
    .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: transparent;
            justify-content: center;
            border: 5px solid white;
            border-radius: 20px;
            backdrop-filter: blur(3px);
    
      }

.row {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
}

.border-bottom {
    border-bottom: 2px solid #ccc;
    padding-bottom: 20px;
}

h1 {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 20px;
    color: #ccc;
    text-transform: uppercase;
}

form {
    margin-top: 20px;
}

input[type="text"],
textarea {
    width: 100%;
    padding: 5px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: rgb(160, 124, 77);
}
/* Add this CSS code to your blog.css file */

textarea::placeholder {
  color: #040101; /* Change the color to your desired value */
}


button {
    background-color: #4CAF50;
    color: white;
    border: none;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    border-radius: 5px;
    cursor: pointer;
}

button:hover {
    background-color: #45a049;
}
/* Add this CSS code to your blog.css file */

label[for="id_diet"] {
  color: #fff; /* Set the desired color for the "Diet" label */
}

label[for="id_course"] {
  color:#fff; /* Set the desired color for the "Course" label */
}


/* blog.css */

    </style>

</head>
<body>
    <div class="wrapper">
        <div class="logo">NutriBlend</div> 
        <ul class="menu">
            <li><a href="/addpost/index">Dashboard</a></li>
            <li><a href="/addpost">Add recipie</a></li>
            <li><a href="/search">Search for recipie</a></li>
        
            <li><a href="/signout" id="logout">Logout</a></li>
            
           
           

        </ul>

    </div>
    <center>
        <div class="add">
            <div class="container">

                <div class="row justify-content-center mt-3 content">
                    <div class="col-md-5 col-sm-12 border-bottom">
                        <h1>
                                Add a blog post
                        </h1>
                        <form action="" method="post">
                            {% csrf_token %}
        
                            {{ form }}
                            <br><br>
                            <button type="submit" >Submit!</button>
                        </form>
                    </div>
                </div>
        
                </div>

        </div>
        
    


</center>

</body>
</html>

templates/addpost/blogindex.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mainpage.css' %}">
    <title>MainPage</title>
    <style>
        /* Navbar styles */
        *{
            margin: 0;
            padding: 0;
        }
        body{
            background: url({% static 'background1.jpg' %});

        }
        .wrapper {
        width:100%;
        margin:auto;
       

        
    }
    header {
        font-family: Arial, Helvetica, sans-serif ;
      height: 50vh;
     width: 100%;
     background: url({% static 'header1.jpg' %});
     background-size: cover;
     background-position: center;
     background-repeat: no-repeat;
}


    
    .menu{
        display: flex;
        float: right;
        list-style:none;
        margin-top: 30px;
        margin-left: 100px;
        margin-right: 10px;
       
       
    }
    .menu li{
        display: inline-block;
        margin-left: 10px;
       
    }
    .menu li a{
        color:rgb(21, 121, 114);
        text-decoration: none;
        padding: 10px 20px;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 15px;
    }
    .menu li:first-child {
     margin-left: 0
    }
    .menu li a:hover{
        background: #fff;
        color:#333;
        border-radius: 10px;
    }
    .logo{
        float: left;
        margin-top: 25px;
        margin-left: 10px;
        color: #fff;
        font-size: 1.5em;
        text-transform: uppercase;
        font-weight: bold;
    }
#logout {
  color: #ff0000;
}

/* Dashboard styles */
.dashboard {
  margin-top: 0px;
  padding: 20px;
  padding-top: 0px;
}

.top-navbar {
  display: flex;
  justify-content: flex-end;
}

.blogg {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  
}

.bloogg {
  background-color: #f8f8f8;
  padding: 20px;
  margin-bottom: 20px;
  border-radius: 5px;
  background: transparent;
  border: 5px solid white;
  backdrop-filter: blur(3px);
}
#content {
    color: #f8f8f8;
}

.bloogg p {
  margin: 5px 0;
  color: #f8f8f8;

  
}
.blog{

    background: #3c0505;
   padding: 20px;
   
   
}

.heading{
    font-weight: bold;
    text-transform: uppercase;
    
   
}
.title {
    font-size: 20px;
}


/* Responsive styles */
@media (max-width: 768px) {
  .blogg {
    flex-direction: column;
  }

  .bloogg {
    width: 100%;
  }
}

    </style>
</head>
<body>





    
        <header>
            <div class="wrapper">
                <div class="logo">NutriBlend</div> 
                <ul class="menu">
                    <li><a href="/addpost/index">Dashboard</a></li>
                    <li><a href="/addpost">Add recipie</a></li>
                    <li><a href="/search">Search for recipie</a></li>
                
                    <li><a href="/signout" id="logout">Logout</a></li>
                    
                   
    
                </ul>
    
            </div>
           
        </header>
    
    

    <section class="dashboard" id="dashboard">

        <div class="top-navbar">
            <form action="" method="get">
                
                </form>
            </div>
        </div>
        
        <div class="row justify-content-center mt-3 blogg">
            {% for blog in blog_list %}
            <div class="col-md-5 col-sm-12 border-bottom bloogg">
                <div class="blog">
                    <p class="heading title">{{ blog.title }}</p>
                <!-- <p class="heading">{{ blog.diet }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ blog.course }}</p> -->
               
               <!-- <p class="heading"><strong>{{ blog.author }}</strong> </p> -->
               <!-- <p class="heading"><br>{{ blog.created_on }}</p> -->

                </div>
                
            <!-- <p id="content">{{ blog.body }}</p> -->
            </div>
            {% endfor %} 
        </div>
        
    </div>
    


        
    </section>
    

</body>
</html>

templates/authentication/home.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>NutriBlend</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        body {
            font-family: Arial, Helvetica, sans-serif ;
        }
        header {
            background: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)),url({%static 'cover2.jpg' %});
            height: 100vh;
            background-size: cover;
            background-position: center;
            position: relative;
        }
        .wrapper {
            width:100%;
            margin:auto;
        }
        .menu{
            float: right;
            list-style:none;
            margin-top: 30px;
            margin-right: 10px;
        }
        .menu li{
            display: inline-block;
        }
        .menu li a{
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            text-transform: uppercase;
            font-weight: bold;
            font-size: 15px;
        }
        .menu li a:hover{
            background: #fff;
            color:#333;
            border-radius: 10px;
        }
        .logo{
            float: left;
            margin-top: 25px;
            margin-left: 10px;
            color: #fff;
            font-size: 1.5em;
            text-transform: uppercase;
            font-weight: bold;
        }
        .text{
            position: absolute;
            width: 600px;
            height: 300px;
            margin: 20% 30%;
            text-align: center;
        }
        .text h1{
            text-align: center;
            color: #fff;
            text-transform: uppercase;
            font-size: 60px;
            margin-bottom: 10px;
        }
        .text a{
            background: orange;
            border-radius: 10px;
            padding: 15px 25px;
            text-decoration: none;
            font-weight: bold;
            font-size: 20px;
            letter-spacing: 1px;
            margin-top: 20px;
            display: inline-block;
            color: #fff;

        }
        .text a:hover{
            background: #fff;
            color: #333;

        }
        .text p{
            color: #fff;
            font-size: 30px;
        }
        #log{
            background:orangered ;

        }
        .message-container {
       color: #f2f2f2;
       padding: 0;
       margin-bottom: 0;
        }
        @media (max-width:650px){
            .logo{
                float: none;
                width: 50%;
                text-align: center;
                margin: auto;
                margin-bottom: 5px;
            }
            .menu{
                float: none;
                margin-top: 0;
                text-align: center;
            }
            .menu li a{
                padding: 5px;
                font-size: 11px;
            }
            .text{
                width: 100%;
                height: 100%;
                margin: 30% 0;
            }
            .text h1{
                font-size: 30px;
            }
            .text p{
                font-size: 18px;
            }
            .text a{
                font-size: 12px;
                padding: 10px;
            }
            

        }
    </style>
</head>
<body>
   <header>
        <div class="wrapper">
            <div class="logo">NutriBlend</div> 
            
        <div class="text">
            <h1>NUTRIBLEND</h1>
            <p>Unlock the Boundless Flavor of Wholesome Goodness: Embrace Health and Explore a World of Nutritious Recipes</p>
            <a href="/signup"> Join The Healthy Revolution </a><br>
            <a href="/signin" id="log"> Log In</a>
            {% for message in messages %} 
            <div class="message-container">
                <strong> {{message}} </strong>
                
            </div>
            
            {% endfor %} 
        </div>
        
    

    </header>
                  
            
    

</body>
</html>

templates/authentication/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>



    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <title>Log In</title>
    <style>
        
        body{
            background-image: url({%static 'cover4.jpg' %});
            background-size: cover;
            background-repeat:no-repeat ;
            background-position: center;
            display: flex;
            justify-content: flex-end;
            align-items: center;
        }
        .wrapper {
            width:100%;
            margin:auto;
            
        }
        header {
            font-family: Arial, Helvetica, sans-serif ;
            height: 100vh;
            width: 100%;
            
            
            
        }
    
        
        .menu{
            display: flex;
            float: right;
            list-style:none;
            margin-top: 30px;
            margin-left: 100px;
            margin-right: 10px;
           
           
        }
        .menu li{
            display: inline-block;
            margin-left: 10px;
           
        }
        .menu li a{
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            text-transform: uppercase;
            font-weight: bold;
            font-size: 15px;
        }
        .menu li:first-child {
         margin-left: 0
        }
        .menu li a:hover{
            background: #fff;
            color:#333;
            border-radius: 10px;
        }
        .logo{
            float: left;
            margin-top: 25px;
            margin-left: 10px;
            color: #fff;
            font-size: 1.5em;
            text-transform: uppercase;
            font-weight: bold;
        }
        p{
            position: relative;
            color: white;
            font-size: 20px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
             left:5px;
        }
        .topHeader{
            font-size: 30px;
            position: relative;
            left: 30px;
            bottom: 40px;
            font-family: Comic Sans MS;
            color: #fff;
        }
        .formBox{
            display: flex;
            position: relative;
            padding: 80px;
            width:400px;
            height: 450px;
            background: transparent;
            justify-content: center;
            border: 5px solid white;
            border-radius: 20px;
            backdrop-filter: blur(3px);
            margin-top: 70px;
            margin-right: 40px;
        }
        .formContainer{
            display: flex;
            flex-direction: column;
    
        }
        .inputText{
            height: 40px;
            width: 100%;
            border:none;
            outline: none;
            border-radius: 30px;
            padding: 0 0 0 20px;
            opacity: 90%;
            color: black;
        }
        ::-webkit-input-placeholder{
            color: rgb(49, 48, 48);
        }
        #SubmitButton{
            height: 40px;
            width: 100%;
            border: none;
            outline: none;
            border-radius: 30px;
            color: black;
            font-family: Comic Sans MS;
            background-color: orange;
        }
        a{
            color: aliceblue;
        }
        .message-container {
        color: #f2f2f2;
        padding: 0;
        margin-bottom: 0;
    }
    
    .message {
        font-weight: bold;
        color: white;
    }
    
    </style>

</head>
<body>
    <header>
        <div class="wrapper">
            <div class="logo">NutriBlend</div> 
            

        </div>
       
    </header>
    <div class="formBox">
        <div class="formContainer">
            <div class="topHeader">
                <h1>Log In</h1>
                

            </div>
            <form action="/signin" method="post">
                {% csrf_token %}
                <input type="text" class="inputText" name="username" placeholder="Username..." required>
                <i class="fa-solid fa-user"></i><br>                     
                <input type="password" class="inputText" name="password" placeholder="Password..." required>
                <i class="fa-solid fa-key"></i><br>
                <input type="submit" name="" id="SubmitButton" value="Log in">

            </form><br>
            <p>No Account? <a href="/signup">Sign Up</a></p>
                              
            {% for message in messages %} 
            <div class="alert-successful">
            {{message}}
            </div>
            {% endfor %}
    
           
        </div>
    </div>


 



 


    

                  

        

</body>
</html>

templates/authentication/signup.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'signup.css' %}">
    <title>Sign Up</title>
</head>
<style>
        
    body{
        background-image: url({%static 'cover4.jpg' %});
        background-size: cover;
        background-repeat:no-repeat ;
        background-position: center;
        display: flex;
        justify-content: flex-end;
        align-items: center;
    }
    .wrapper {
        width:100%;
        margin:auto;
        
    }
    header {
        font-family: Arial, Helvetica, sans-serif ;
        height: 100vh;
        width: 100%;
        
        
        
    }

    
    .menu{
        display: flex;
        float: right;
        list-style:none;
        margin-top: 30px;
        margin-left: 100px;
        margin-right: 10px;
       
       
    }
    .menu li{
        display: inline-block;
        margin-left: 10px;
       
    }
    .menu li a{
        color: #fff;
        text-decoration: none;
        padding: 10px 20px;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 15px;
    }
    .menu li:first-child {
     margin-left: 0
    }
    .menu li a:hover{
        background: #fff;
        color:#333;
        border-radius: 10px;
    }
    .logo{
        float: left;
        margin-top: 25px;
        margin-left: 10px;
        color: #fff;
        font-size: 1.5em;
        text-transform: uppercase;
        font-weight: bold;
    }
    p{
        position: relative;
        color: white;
        font-size: 20px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
         left:5px;
    }
    .topHeader{
        font-size: 30px;
        position: relative;
        left: 30px;
        bottom: 40px;
        font-family: Comic Sans MS;
        color: #fff;
    }
    .formBox{
        display: flex;
        position: relative;
        padding: 80px;
        width:400px;
        height: 450px;
        background: transparent;
        justify-content: center;
        border: 5px solid white;
        border-radius: 20px;
        backdrop-filter: blur(3px);
        margin-top: 70px;
        margin-right: 40px;
    }
    .formContainer{
        display: flex;
        flex-direction: column;

    }
    .inputText{
        height: 40px;
        width: 100%;
        border:none;
        outline: none;
        border-radius: 30px;
        padding: 0 0 0 20px;
        opacity: 90%;
        color: black;
    }
    ::-webkit-input-placeholder{
        color: rgb(49, 48, 48);
    }
    #SubmitButton{
        height: 40px;
        width: 100%;
        border: none;
        outline: none;
        border-radius: 30px;
        color: black;
        font-family: Comic Sans MS;
        background-color: orange;
    }
    a{
        color: aliceblue;
    }
    .message-container {
    color: #f2f2f2;
    padding: 0;
    margin-bottom: 0;
}

.message {
    font-weight: bold;
    color: white;
}

</style>
<body>
    <header>
        <div class="wrapper">
            <div class="logo">NutriBlend</div> 
            

        </div>
       
    </header>
    <div class="formBox">
        <div class="formContainer">
            <div class="topHeader">
                <h1>Sign Up</h1>
                

            </div>
            <form action="/signup" method="post">
                {% csrf_token %}
                <input type="text" class="inputText" name="username" placeholder="Username..." required>
                <i class="fa-solid fa-user"></i><br> 
                <input type="text" class="inputText" name="name" placeholder="Name..." required>
                <i class="fa-solid fa-key"></i><br>                    
                <input type="password" class="inputText" name="password" placeholder="Password..." required>
                <i class="fa-solid fa-key"></i><br>
                <input type="submit" name="" id="SubmitButton" value="Sign Up">

            </form><br>
            <p>Already a member?<a href="/signin">Log In</a></p>
            {% for message in messages %} 
    <div class="message-container">
        <strong>Message: </strong>
        <span class="message">{{ message }}</span>
    </div>
{% endfor %}
           
        </div>
        
    </div>
    

     
    

                
</body>
</html>

templates/profilec/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'mainpage.css' %}">
    <title>MainPage</title>
</head>
<body>





    <header>

    
        <nav class="navbar">
            <hr>
            <ul>
                <li><a href="/profilec">Dashboard</a></li>
                <li><a href="/addpost">Add recipie</a></li>
                
                <li><a href="/signout" id="logout">Logout</a></li>

                
            </ul>
        </nav>
    
    </header>

    <section class="dashboard" id="dashboard">

        <div class="top-navbar">
            <form action="" method="get">
                <input class="form-input" type="text" placeholder="Search here" name="query">
           <!-- this should be the drop down  -->
                    <button type="submit">Submit!</button>
                </form>
            </div>
        </div>


        
    </section>
    

</body>
</html>